name: firecrawl

x-common-service: &common-service
  # NOTE: If you want to build the service locally,
  # uncomment the build: statement and comment out the image: statement
  # image: ghcr.io/mendableai/firecrawl
  build: 
    context: apps/api
  restart: always

  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  networks:
    - backend
  extra_hosts:
    - "host.docker.internal:host-gateway"
  deploy:
    resources:
      limits:
        memory: 16G
      reservations:
        memory: 8G

x-common-env: &common-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}
  REDIS_RATE_LIMIT_URL: ${REDIS_URL:-redis://redis:6379}
  PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000/scrape}
  USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL}
  MODEL_NAME: ${MODEL_NAME}
  MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME} 
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL} 
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
  BULL_AUTH_KEY: ${BULL_AUTH_KEY}
  TEST_API_KEY: ${TEST_API_KEY}
  POSTHOG_API_KEY: ${POSTHOG_API_KEY}
  POSTHOG_HOST: ${POSTHOG_HOST}
  SUPABASE_ANON_TOKEN: ${SUPABASE_ANON_TOKEN}
  SUPABASE_URL: ${SUPABASE_URL}
  SUPABASE_SERVICE_TOKEN: ${SUPABASE_SERVICE_TOKEN}
  SCRAPING_BEE_API_KEY: ${SCRAPING_BEE_API_KEY}
  SELF_HOSTED_WEBHOOK_URL: ${SELF_HOSTED_WEBHOOK_URL}
  SERPER_API_KEY: ${SERPER_API_KEY}
  SEARCHAPI_API_KEY: ${SEARCHAPI_API_KEY}
  LOGGING_LEVEL: ${LOGGING_LEVEL}
  PROXY_SERVER: core-residential.evomi.com:1000
  PROXY_USERNAME: happyocea3
  PROXY_PASSWORD: Gpvo1W5Dtt8eRJHDhkXo_country-US
  SEARXNG_ENDPOINT: ${SEARXNG_ENDPOINT}
  SEARXNG_ENGINES: ${SEARXNG_ENGINES}
  SEARXNG_CATEGORIES: ${SEARXNG_CATEGORIES}
  # GCP Configuration
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/credentials.json
  GCP_BUCKET: ${GCP_BUCKET:-firecrawl-backups}

services:
  playwright-service:
    build: apps/playwright-service-ts
    restart: always
    environment:
      PORT: 3000
      PROXY_SERVER: core-residential.evomi.com:1000
      PROXY_USERNAME: happyocea3
      PROXY_PASSWORD: Gpvo1W5Dtt8eRJHDhkXo_country-US
      BLOCK_MEDIA: true
      # Browser optimization settings
      BROWSER_CONTEXT_OPTIONS: '{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","viewport":{"width":1920,"height":1080},"deviceScaleFactor":1,"isMobile":false,"hasTouch":false,"javaScriptEnabled":true}'
      MAX_CONCURRENT_PAGES: 10
      PAGE_TIMEOUT: 30000
      RETRY_COUNT: 1
      RETRY_DELAY: 10000
      PROXY_TIMEOUT: 60000
      PROXY_RETRY_COUNT: 5
      PROXY_RETRY_DELAY: 15000
      # Proxy rotation settings
      PROXY_ROTATION_ENABLED: true
      PROXY_ROTATION_INTERVAL: 1
      PROXY_ROTATION_429_WAIT: 30000
      PROXY_MAX_REQUESTS: 100
      # Rate limiting
      RATE_LIMIT_ENABLED: true
      RATE_LIMIT_REQUESTS: 10
      RATE_LIMIT_WINDOW: 60000
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 70G
          cpus: '16'
        reservations:
          memory: 48G
          cpus: '8'

  api:
    <<: *common-service
    environment:
      <<: *common-env
      HOST: "0.0.0.0"
      PORT: ${INTERNAL_PORT:-3002}
      FLY_PROCESS_GROUP: app
    depends_on:
      - redis
      - playwright-service
    ports:
      - "${PORT:-3002}:${INTERNAL_PORT:-3002}"
    command: [ "pnpm", "run", "start:production" ]
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4'
        reservations:
          memory: 8G
          cpus: '2'

  worker:
    <<: *common-service
    build:
      context: apps/api
      dockerfile: Dockerfile
      target: base
    environment:
      <<: *common-env
      FLY_PROCESS_GROUP: worker
      MAX_RAM: 0.92
      # Queue configuration
      BULL_CONCURRENCY: 3
      BULL_LIMITER_MAX: 30
      BULL_LIMITER_DURATION: 60000
      BULL_LOCK_DURATION: 200000
      BULL_STALLED_INTERVAL: 60000
      BULL_REMOVE_ON_COMPLETE: true
      BULL_REMOVE_ON_FAIL: true
      BULL_ATTEMPTS: 5
      BULL_BACKOFF: 15000
      # Google Cloud SDK PATH
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/google-cloud-sdk/bin
    depends_on:
      - redis
      - playwright-service
      - api
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y curl python3 python3-pip apt-transport-https ca-certificates gnupg git &&
      mkdir -p /var/secrets/google /app/data/crawl_backups &&
      cd /app &&
      npm install @google-cloud/storage &&
      GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/credentials.json node -e \"const {Storage} = require('@google-cloud/storage'); console.log('GCP Storage initialized')\" &&
      pnpm run workers"
    volumes:
      - /Users/jj/code/gdrive-410709-7f394f22402f.json:/var/secrets/google/credentials.json:ro
      - ./data/crawl_backups:/app/data/crawl_backups
      - ./apps/api/src:/app/src
    deploy:
      resources:
        limits:
          memory: 48G
          cpus: '8'
        reservations:
          memory: 32G
          cpus: '4'

  redis:
    # NOTE: If you want to use Valkey (open source) instead of Redis (source available),
    # uncomment the Valkey statement and comment out the Redis statement.
    # Using Valkey with Firecrawl is untested and not guaranteed to work. Use with caution.
    # image: redis:alpine
    image: redis/redis-stack:latest
    # image: valkey/valkey:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0 --maxmemory 20gb --maxmemory-policy allkeys-lru --loadmodule /opt/redis-stack/lib/redisbloom.so --protected-mode no
    deploy:
      resources:
        limits:
          memory: 24G
        reservations:
          memory: 16G

networks:
  backend:
    driver: bridge
