apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"api","namespace":"firecrawl-prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"api"}},"template":{"metadata":{"labels":{"app":"api"}},"spec":{"containers":[{"args":["pnpm","run","start:production"],"env":[{"name":"FLY_PROCESS_GROUP","value":"app"}],"envFrom":[{"configMapRef":{"name":"firecrawl-config"}},{"secretRef":{"name":"firecrawl-secret"}}],"image":"gcr.io/gdrive-410709/firecrawl-api:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/v0/health/liveness","port":3002},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5},"name":"api","ports":[{"containerPort":3002}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/v0/health/readiness","port":3002},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5}}],"imagePullSecrets":[{"name":"gcr-access"}]}}}}
  creationTimestamp: "2025-04-15T09:46:17Z"
  generation: 4
  name: api
  namespace: firecrawl-prod
  resourceVersion: "1228700"
  uid: c3c3ec42-502f-4e47-9529-0868a98436c0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-15T12:18:22+02:00"
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - args:
        - pnpm
        - run
        - start:production
        command:
        - node
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firecrawl-secret
              key: REDIS_PASSWORD
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "3002"
        - name: FLY_PROCESS_GROUP
          value: app
        envFrom:
        - configMapRef:
            name: firecrawl-config
        image: gcr.io/gdrive-410709/firecrawl-api:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v0/health/liveness
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: api
        ports:
        - containerPort: 3002
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v0/health/readiness
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-access
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-15T09:46:17Z"
    lastUpdateTime: "2025-04-15T09:46:17Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-16T10:48:11Z"
    lastUpdateTime: "2025-04-16T10:48:11Z"
    message: ReplicaSet "api-66d9779779" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 4
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
