apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-service
  namespace: firecrawl-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-service
  template:
    metadata:
      labels:
        app: playwright-service
    spec:
      containers:
      - name: playwright-service
        image: gcr.io/gdrive-410709/firecrawl-playwright:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: firecrawl-config
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  namespace: firecrawl-prod
spec:
  selector:
    app: playwright-service
  ports:
    - port: 3000
      targetPort: 3000 