apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"playwright-service","namespace":"firecrawl-prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"playwright-service"}},"template":{"metadata":{"labels":{"app":"playwright-service"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"playwright-service-config"}}],"image":"gcr.io/gdrive-410709/firecrawl-playwright:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health/liveness","port":3000},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5},"name":"playwright-service","ports":[{"containerPort":3000}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health/readiness","port":3000},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5}}],"imagePullSecrets":[{"name":"gcr-access"}]}}}}
  creationTimestamp: "2025-04-15T09:46:14Z"
  generation: 4
  name: playwright-service
  namespace: firecrawl-prod
  resourceVersion: "1228701"
  uid: 389b51ad-2439-4a07-8016-b88c341ff89a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: playwright-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-15T12:18:22+02:00"
      creationTimestamp: null
      labels:
        app: playwright-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: playwright-service-config
        image: gcr.io/gdrive-410709/firecrawl-playwright:latest
        imagePullPolicy: Always
        name: playwright-service
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-access
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-15T09:46:14Z"
    lastUpdateTime: "2025-04-15T09:46:14Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-16T10:48:11Z"
    lastUpdateTime: "2025-04-16T10:48:11Z"
    message: ReplicaSet "playwright-service-68d9745464" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 4
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
