apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: firecrawl-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node.kubernetes.io/disk-pressure
                operator: DoesNotExist
      containers:
      - name: worker
        image: gcr.io/gdrive-410709/firecrawl-worker:latest
        imagePullPolicy: IfNotPresent
        args: ["pnpm", "run", "workers"]
        env:
        - name: FLY_PROCESS_GROUP
          value: worker
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: REDIS_PASSWORD
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        envFrom:
        - configMapRef:
            name: firecrawl-config
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        livenessProbe:
          exec:
            command:
            - pnpm
            - run
            - health:worker
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["pnpm", "run", "graceful-shutdown"]
        volumeMounts:
        - name: gcs-creds
          mountPath: /var/secrets/google
          readOnly: true
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: gcs-creds
        secret:
          secretName: gcs-credentials 